#!/usr/bin/env python2

# General purpose image converter.
# Automatic recognition~~
# Handy utility for physics experiments

# Example(converting all bmp file to jpg):
# ls|grep BMP|parallel ./imgconv {} {.}.jpg

import sys
from SimpleCV import *
Image(sys.argv[1]).save(sys.argv[2]);
